"""Merchant onboarding: the two entry paths and the codes that connect them.

Flow A (dashboard first):  a signed-in user creates a merchant -> gets a LINK code ->
                           texts `connect: CODE` on WhatsApp -> the number is linked to the store.
Flow B (WhatsApp first):   a merchant registers on WhatsApp -> gets a CLAIM code ->
                           signs in on the dashboard and enters it -> becomes the owner.

IDs are generated by Postgres (RETURNING). Every public function that writes is one
atomic unit: it commits on success and rolls back on any error. Pooled callers can keep
using `with get_db() as conn:`; the extra commit is harmless.
"""
import re
import secrets
from contextlib import contextmanager
from dataclasses import dataclass
from uuid import UUID

import psycopg

from validation.models import ConnectCode, ConnectCodePurpose, Merchant, Tier

# Matches the ConnectCode model pattern: 8 characters, no I, O, 0 or 1.
CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
CODE_LENGTH = 8
_CODE_PATTERN = re.compile(r"^[A-HJ-NP-Z2-9]{8}$")

# Placeholders. A link code is used within minutes (the user is looking at the dashboard);
# a claim code is sent over WhatsApp and may be used later, but it grants ownership.
LINK_CODE_TTL_HOURS = 1
CLAIM_CODE_TTL_HOURS = 24

MAX_BUSINESS_NAME_CHARS = 100
_E164 = re.compile(r"^\+[1-9][0-9]{7,14}$")

# One message for every failure, so the response never reveals whether a code exists.
INVALID_CODE_MESSAGE = "Invalid or expired connect code"

_CODE_COLUMNS = (
    "code, purpose, store_id, created_by_user_id, expires_at, used_at, used_by_user_id, created_at"
)


class WhatsAppNumberInUseError(ValueError):
    """The number is already connected to another business."""

    def __init__(self):
        super().__init__("This WhatsApp number is already connected to another business")


@dataclass
class MerchantContext:
    merchant: Merchant
    store_id: UUID
    source_id: UUID

    # Convenience, so callers can read merchant fields straight off the context.
    @property
    def merchant_id(self) -> UUID:
        return self.merchant.merchant_id

    @property
    def business_name(self) -> str:
        return self.merchant.business_name

    @property
    def tier(self) -> Tier:
        return self.merchant.tier

    @property
    def created_at(self):
        return self.merchant.created_at


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
@contextmanager
def _atomic(conn):
    try:
        yield
        conn.commit()
    except Exception:
        conn.rollback()
        raise


def _as_uuid(value) -> UUID:
    return value if isinstance(value, UUID) else UUID(str(value))


def normalize_whatsapp_number(value: str) -> str:
    """'whatsapp:+27 82 123 4567' -> '+27821234567'. Raises ValueError if not E.164."""
    number = (value or "").strip().replace("whatsapp:", "").replace(" ", "")
    if not _E164.match(number):
        raise ValueError("Invalid WhatsApp number")
    return number


def _clean_business_name(name: str) -> str:
    cleaned = " ".join((name or "").split())
    if not cleaned or len(cleaned) > MAX_BUSINESS_NAME_CHARS:
        raise ValueError(f"Business name must be 1 to {MAX_BUSINESS_NAME_CHARS} characters")
    return cleaned


def _normalize_code(code) -> str:
    normalized = (code or "").strip().upper() if isinstance(code, str) else ""
    if not _CODE_PATTERN.match(normalized):
        raise ValueError(INVALID_CODE_MESSAGE)
    return normalized


def generate_connect_code() -> str:
    """A random code from a cryptographically secure source."""
    return "".join(secrets.choice(CODE_ALPHABET) for _ in range(CODE_LENGTH))


def _row_to_code(row) -> ConnectCode:
    return ConnectCode(
        code=row[0],
        purpose=row[1],
        store_id=row[2],
        created_by_user_id=row[3],
        expires_at=row[4],
        used_at=row[5],
        used_by_user_id=row[6],
        created_at=row[7],
    )


# ---------------------------------------------------------------------------
# Lookups
# ---------------------------------------------------------------------------
def get_merchant_by_number(whatsapp_number: str, conn) -> MerchantContext | None:
    try:
        number = normalize_whatsapp_number(whatsapp_number)
    except ValueError:
        return None

    with conn.cursor() as cur:
        cur.execute(
            """SELECT m.merchant_id, m.business_name, m.location, m.tier, m.created_at,
                      s.store_id, ds.source_id
               FROM data_sources ds
               JOIN stores s ON s.store_id = ds.store_id
               JOIN merchants m ON m.merchant_id = s.merchant_id
               WHERE ds.source_type = 'whatsapp'
                 AND ds.is_active
                 AND ds.external_identifier = %s""",
            (number,),
        )
        row = cur.fetchone()

    if row is None:
        return None

    merchant = Merchant(
        merchant_id=row[0],
        business_name=row[1],
        location=row[2],
        tier=row[3],
        created_at=row[4],
    )
    return MerchantContext(merchant=merchant, store_id=row[5], source_id=row[6])


# ---------------------------------------------------------------------------
# Row-level building blocks (no commit; callers wrap them in _atomic)
# ---------------------------------------------------------------------------
def _insert_merchant_and_store(cur, business_name: str, store_name: str | None = None):
    cur.execute(
        """INSERT INTO merchants (business_name, tier)
           VALUES (%s, %s) RETURNING merchant_id, created_at""",
        (business_name, Tier.INSIGHTS.value),
    )
    merchant_id, created_at = cur.fetchone()

    cur.execute(
        """INSERT INTO stores (merchant_id, store_name)
           VALUES (%s, %s) RETURNING store_id""",
        (merchant_id, store_name or business_name),
    )
    store_id = cur.fetchone()[0]

    merchant = Merchant(
        merchant_id=merchant_id,
        business_name=business_name,
        tier=Tier.INSIGHTS,
        created_at=created_at,
    )
    return merchant, store_id


def _link_whatsapp(cur, store_id, number: str) -> UUID:
    """Attach a WhatsApp number to a store. Idempotent for the same store; raises
    WhatsAppNumberInUseError if another business already has the number."""
    store_id = _as_uuid(store_id)
    cur.execute(
        """INSERT INTO data_sources (store_id, source_name, source_type, external_identifier)
           VALUES (%s, 'WhatsApp', 'whatsapp', %s)
           ON CONFLICT (external_identifier)
               WHERE source_type = 'whatsapp' AND is_active
           DO NOTHING
           RETURNING source_id""",
        (store_id, number),
    )
    row = cur.fetchone()
    if row is not None:
        return row[0]

    cur.execute(
        """SELECT source_id, store_id FROM data_sources
           WHERE source_type = 'whatsapp' AND is_active AND external_identifier = %s""",
        (number,),
    )
    existing = cur.fetchone()
    if existing is not None and existing[1] == store_id:
        return existing[0]
    raise WhatsAppNumberInUseError()


def _create_whatsapp_merchant_rows(cur, number: str, business_name: str) -> MerchantContext:
    merchant, store_id = _insert_merchant_and_store(cur, business_name)
    source_id = _link_whatsapp(cur, store_id, number)
    return MerchantContext(merchant=merchant, store_id=store_id, source_id=source_id)


def _create_code(cur, store_id, purpose: ConnectCodePurpose, created_by_user_id, ttl_hours: int):
    if purpose == ConnectCodePurpose.LINK_WHATSAPP and created_by_user_id is None:
        raise ValueError("link_whatsapp codes must be created by a signed-in user")

    # Only one live code per store and purpose: issuing a new one replaces the old.
    cur.execute(
        "DELETE FROM connect_codes WHERE store_id = %s AND purpose = %s AND used_at IS NULL",
        (store_id, purpose.value),
    )
    for _ in range(5):
        cur.execute(
            f"""INSERT INTO connect_codes (code, purpose, store_id, created_by_user_id, expires_at)
                VALUES (%s, %s, %s, %s, now() + make_interval(hours => %s))
                ON CONFLICT (code) DO NOTHING
                RETURNING {_CODE_COLUMNS}""",
            (generate_connect_code(), purpose.value, store_id, created_by_user_id, ttl_hours),
        )
        row = cur.fetchone()
        if row is not None:
            return _row_to_code(row)
    raise RuntimeError("Could not generate a unique connect code")


def _consume_code(cur, code, purpose: ConnectCodePurpose, *, used_by_user_id=None, expected_store_id=None):
    """Atomically mark a live code of this purpose as used, or raise ValueError.

    One UPDATE does the check and the use together, so two simultaneous redemptions
    of the same code can't both succeed.
    """
    normalized = _normalize_code(code)

    sql = f"""UPDATE connect_codes
              SET used_at = now(), used_by_user_id = %s
              WHERE code = %s AND purpose = %s
                AND used_at IS NULL AND expires_at > now()"""
    params = [used_by_user_id, normalized, purpose.value]
    if expected_store_id is not None:
        sql += " AND store_id = %s"
        params.append(_as_uuid(expected_store_id))
    sql += f" RETURNING {_CODE_COLUMNS}"

    cur.execute(sql, params)
    row = cur.fetchone()
    if row is None:
        raise ValueError(INVALID_CODE_MESSAGE)
    return _row_to_code(row)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
def create_merchant(whatsapp_number: str, business_name: str, conn) -> MerchantContext:
    """Register a merchant from WhatsApp (merchant + store + WhatsApp source).

    If the number is already registered (for example two messages arrive at the same
    moment), returns the existing merchant instead of failing.
    """
    number = normalize_whatsapp_number(whatsapp_number)
    name = _clean_business_name(business_name)

    try:
        with _atomic(conn), conn.cursor() as cur:
            return _create_whatsapp_merchant_rows(cur, number, name)
    except WhatsAppNumberInUseError:
        existing = get_merchant_by_number(number, conn)
        if existing is not None:
            return existing
        raise


def create_whatsapp_merchant(whatsapp_number: str, business_name: str, conn, *, code_ttl_hours: int | None = None):
    """Flow B: register from WhatsApp and issue the CLAIM code to send back to the merchant."""
    number = normalize_whatsapp_number(whatsapp_number)
    name = _clean_business_name(business_name)

    with _atomic(conn), conn.cursor() as cur:
        context = _create_whatsapp_merchant_rows(cur, number, name)
        code = _create_code(
            cur, context.store_id, ConnectCodePurpose.CLAIM_MERCHANT, None,
            code_ttl_hours or CLAIM_CODE_TTL_HOURS,
        )

    return {
        "merchant_id": context.merchant_id,
        "store_id": context.store_id,
        "source_id": context.source_id,
        "connect_code": code.code,
        "expires_at": code.expires_at,
    }


def create_dashboard_merchant(user_id, business_name: str, conn, *, store_name: str | None = None, code_ttl_hours: int | None = None):
    """Flow A: a signed-in user creates a merchant and gets the LINK code to text on WhatsApp."""
    user = _as_uuid(user_id)
    name = _clean_business_name(business_name)
    store = _clean_business_name(store_name) if store_name else None

    with _atomic(conn), conn.cursor() as cur:
        merchant, store_id = _insert_merchant_and_store(cur, name, store)
        cur.execute(
            "INSERT INTO merchant_users (user_id, merchant_id, role) VALUES (%s, %s, 'owner')",
            (user, merchant.merchant_id),
        )
        code = _create_code(
            cur, store_id, ConnectCodePurpose.LINK_WHATSAPP, user,
            code_ttl_hours or LINK_CODE_TTL_HOURS,
        )

    return {
        "merchant_id": merchant.merchant_id,
        "store_id": store_id,
        "connect_code": code.code,
        "expires_at": code.expires_at,
    }


def create_connect_code(store_id, purpose: ConnectCodePurpose, *, conn, created_by_user_id=None, expires_in_hours: int | None = None) -> ConnectCode:
    """Issue a fresh code for a store, replacing any unused code of the same purpose."""
    purpose = ConnectCodePurpose(purpose)
    default_ttl = (
        LINK_CODE_TTL_HOURS if purpose == ConnectCodePurpose.LINK_WHATSAPP else CLAIM_CODE_TTL_HOURS
    )
    user = _as_uuid(created_by_user_id) if created_by_user_id is not None else None

    with _atomic(conn), conn.cursor() as cur:
        return _create_code(cur, _as_uuid(store_id), purpose, user, expires_in_hours or default_ttl)


def link_whatsapp_source_to_store(store_id, whatsapp_number: str, conn) -> UUID:
    number = normalize_whatsapp_number(whatsapp_number)
    with _atomic(conn), conn.cursor() as cur:
        return _link_whatsapp(cur, store_id, number)


def redeem_dashboard_connect_code(code: str, user_id, conn, *, expected_store_id=None) -> ConnectCode:
    """Flow B, dashboard side: a signed-in user claims a WhatsApp-created merchant.

    Consumes the code and makes the user the owner in one transaction. If the business
    already has an owner, nothing is consumed.
    """
    user = _as_uuid(user_id)

    with _atomic(conn), conn.cursor() as cur:
        consumed = _consume_code(
            cur, code, ConnectCodePurpose.CLAIM_MERCHANT,
            used_by_user_id=user, expected_store_id=expected_store_id,
        )
        cur.execute("SELECT merchant_id FROM stores WHERE store_id = %s", (consumed.store_id,))
        merchant_id = cur.fetchone()[0]
        try:
            cur.execute(
                "INSERT INTO merchant_users (user_id, merchant_id, role) VALUES (%s, %s, 'owner')",
                (user, merchant_id),
            )
        except psycopg.errors.UniqueViolation:
            raise ValueError("This business has already been claimed")

    return consumed


def redeem_whatsapp_connect_code(code: str, whatsapp_number: str, conn, *, expected_store_id=None) -> ConnectCode:
    """Flow A, WhatsApp side: link the sender's number to the dashboard merchant's store.

    If the number already belongs to another business, nothing is consumed.
    """
    number = normalize_whatsapp_number(whatsapp_number)

    with _atomic(conn), conn.cursor() as cur:
        consumed = _consume_code(
            cur, code, ConnectCodePurpose.LINK_WHATSAPP, expected_store_id=expected_store_id,
        )
        _link_whatsapp(cur, consumed.store_id, number)

    return consumed