from database.connection import get_direct_connection

# Fresh-database bootstrap for Neon Postgres.
# - IDs are UUIDs generated by Postgres (gen_random_uuid() is built in, no extension needed).
# - merchant_users.user_id is the Neon Auth user id (the JWT `sub`), i.e. neon_auth."user".id.
#   No FK is declared so this file doesn't depend on the neon_auth schema existing.
# - CREATE ... IF NOT EXISTS is safe to re-run but cannot ALTER existing tables.
#   Drop the old tables first when moving from the TEXT-ID schema.

SCHEMA_STATEMENTS = [
    # ---------------------------------------------------------------- merchants
    """
    CREATE TABLE IF NOT EXISTS merchants (
        merchant_id   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        business_name TEXT NOT NULL,
        location      TEXT,
        tier          TEXT NOT NULL DEFAULT 'insights'
                      CHECK (tier IN ('insights', 'full')),
        created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    """,
    # ---------------------------------------------------------- merchant_users
    # A merchant can exist with no users (WhatsApp-first, not yet claimed).
    """
    CREATE TABLE IF NOT EXISTS merchant_users (
        user_id     UUID NOT NULL,
        merchant_id UUID NOT NULL
                    REFERENCES merchants(merchant_id) ON DELETE CASCADE,
        role        TEXT NOT NULL DEFAULT 'owner'
                    CHECK (role IN ('owner', 'admin', 'employee', 'viewer')),
        created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (user_id, merchant_id)
    );
    """,
    # ------------------------------------------------------------------ stores
    """
    CREATE TABLE IF NOT EXISTS stores (
        store_id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        merchant_id UUID NOT NULL
                    REFERENCES merchants(merchant_id) ON DELETE CASCADE,
        store_name  TEXT NOT NULL,
        location    TEXT,
        created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (merchant_id, store_name)
    );
    """,
    # ------------------------------------------------------------ data_sources
    # UNIQUE (source_id, store_id) lets transactions use a composite FK so a
    # transaction can never pair store A with a source belonging to store B.
    # For WhatsApp, external_identifier is the sender's number in E.164 (+27...).
    """
    CREATE TABLE IF NOT EXISTS data_sources (
        source_id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        store_id            UUID NOT NULL
                            REFERENCES stores(store_id) ON DELETE CASCADE,
        source_name         TEXT NOT NULL,
        source_type         TEXT NOT NULL
                            CHECK (source_type IN (
                                'pos', 'bank_statement', 'accounting_software',
                                'online_store', 'whatsapp', 'csv', 'manual'
                            )),
        external_identifier TEXT,
        is_active           BOOLEAN NOT NULL DEFAULT TRUE,
        created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (source_id, store_id),
        CHECK (
            source_type <> 'whatsapp'
            OR external_identifier ~ '^\\+[1-9][0-9]{7,14}$'
        )
    );
    """,
    # One active WhatsApp number can belong to only one store. Also serves the webhook lookup.
    """
    CREATE UNIQUE INDEX IF NOT EXISTS uniq_whatsapp_number
        ON data_sources (external_identifier)
        WHERE source_type = 'whatsapp' AND is_active;
    """,
    # ----------------------------------------------------------- connect_codes
    # purpose = 'link_whatsapp' : dashboard-first, user texts the code to the bot
    # purpose = 'claim_merchant': WhatsApp-first, user enters the code on the dashboard
    # The merchant is derived from the store, so the two can never disagree.
    # Consume atomically:
    #   UPDATE connect_codes SET used_at = now()
    #   WHERE code = %s AND purpose = %s AND used_at IS NULL AND expires_at > now()
    #   RETURNING store_id;
    """
    CREATE TABLE IF NOT EXISTS connect_codes (
        code            TEXT PRIMARY KEY,
        purpose         TEXT NOT NULL
                        CHECK (purpose IN ('link_whatsapp', 'claim_merchant')),
        store_id        UUID NOT NULL
                        REFERENCES stores(store_id) ON DELETE CASCADE,
        expires_at      TIMESTAMPTZ NOT NULL,
        used_at         TIMESTAMPTZ,
        used_by_user_id UUID,
        created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
        CHECK (expires_at > created_at),
        CHECK (used_at IS NULL OR used_by_user_id IS NOT NULL)
    );
    """,
    # --------------------------------------------------------------- offerings
    """
    CREATE TABLE IF NOT EXISTS offerings (
        offering_id   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        store_id      UUID NOT NULL
                      REFERENCES stores(store_id) ON DELETE CASCADE,
        offering_name TEXT NOT NULL,
        created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    """,
    # Case-insensitive uniqueness so "Shirt" and "shirt" are one offering.
    # get_or_create_offering should upsert against this index.
    """
    CREATE UNIQUE INDEX IF NOT EXISTS uniq_offering_per_store
        ON offerings (store_id, lower(offering_name));
    """,
    # ------------------------------------------------------------ transactions
    """
    CREATE TABLE IF NOT EXISTS transactions (
        transaction_id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        store_id            UUID NOT NULL,
        source_id           UUID NOT NULL,
        offering_id         UUID REFERENCES offerings(offering_id) ON DELETE RESTRICT,
        quantity            INTEGER CHECK (quantity IS NULL OR quantity > 0),
        input_type          TEXT NOT NULL
                            CHECK (input_type IN (
                                'pos_tap', 'voice', 'manual', 'whatsapp', 'csv', 'api'
                            )),
        amount_zar          NUMERIC(12, 2) NOT NULL CHECK (amount_zar > 0),
        payment_method      TEXT CHECK (payment_method IN ('cash', 'digital')),
        raw_message         TEXT,
        whatsapp_message_id TEXT UNIQUE,
        is_voided           BOOLEAN NOT NULL DEFAULT FALSE,
        voided_at           TIMESTAMPTZ,
        void_reason         TEXT,
        transaction_date    TIMESTAMPTZ NOT NULL DEFAULT now(),
        created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
        FOREIGN KEY (store_id)
            REFERENCES stores(store_id) ON DELETE CASCADE,
        FOREIGN KEY (source_id, store_id)
            REFERENCES data_sources(source_id, store_id) ON DELETE RESTRICT,
        CHECK (is_voided = (voided_at IS NOT NULL))
    );
    """,
    # ------------------------------------------------------ financial_snapshots
    """
    CREATE TABLE IF NOT EXISTS financial_snapshots (
        snapshot_id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        store_id                UUID NOT NULL
                                REFERENCES stores(store_id) ON DELETE CASCADE,
        period_start            DATE NOT NULL,
        period_end              DATE NOT NULL,
        total_revenue_zar       NUMERIC(12, 2) NOT NULL CHECK (total_revenue_zar >= 0),
        transaction_count       INTEGER NOT NULL CHECK (transaction_count >= 0),
        average_transaction_zar NUMERIC(12, 2) NOT NULL CHECK (average_transaction_zar >= 0),
        cash_revenue_zar        NUMERIC(12, 2) NOT NULL CHECK (cash_revenue_zar >= 0),
        digital_revenue_zar     NUMERIC(12, 2) NOT NULL CHECK (digital_revenue_zar >= 0),
        revenue_growth_pct      NUMERIC(8, 2),
        revenue_volatility      NUMERIC(12, 4),
        created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
        CHECK (period_end >= period_start),
        UNIQUE (store_id, period_start, period_end)
    );
    """,
    # ----------------------------------------------------------------- indexes
    "CREATE INDEX IF NOT EXISTS idx_merchant_users_merchant ON merchant_users (merchant_id);",
    """
    CREATE UNIQUE INDEX IF NOT EXISTS one_owner_per_merchant
        ON merchant_users (merchant_id) WHERE role = 'owner';
    """,
    "CREATE INDEX IF NOT EXISTS idx_stores_merchant ON stores (merchant_id);",
    "CREATE INDEX IF NOT EXISTS idx_sources_store ON data_sources (store_id);",
    "CREATE INDEX IF NOT EXISTS idx_connect_codes_store ON connect_codes (store_id);",
    "CREATE INDEX IF NOT EXISTS idx_connect_codes_expires ON connect_codes (expires_at);",
    # Dashboard queries: per store, by date, excluding voided rows.
    """
    CREATE INDEX IF NOT EXISTS idx_transactions_store_date_live
        ON transactions (store_id, transaction_date)
        WHERE NOT is_voided;
    """,
    "CREATE INDEX IF NOT EXISTS idx_transactions_source ON transactions (source_id);",
    "CREATE INDEX IF NOT EXISTS idx_transactions_offering ON transactions (offering_id);",
]


def init_database(connection=None):
    owns_connection = connection is None
    conn = connection or get_direct_connection()

    try:
        print("Creating ZakaScore PostgreSQL schema...")
        with conn.cursor() as cursor:
            for statement in SCHEMA_STATEMENTS:
                cursor.execute(statement)
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        if owns_connection:
            conn.close()

    print("PostgreSQL schema initialized successfully.")


if __name__ == "__main__":
    init_database()